import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#fbf8ff',
        surface: '#fbf8ff',
        'surface-dim': '#dad9e3',
        'surface-bright': '#fbf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f2fd',
        'surface-container': '#eeedf7',
        'surface-container-high': '#e8e7f1',
        'surface-container-highest': '#e3e1ec',
        'on-surface': '#1a1b22',
        'on-background': '#1a1b22',
        'on-surface-variant': '#444748',
        'inverse-surface': '#2f3038',
        'inverse-on-surface': '#f1effa',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        'surface-tint': '#5f5e5e',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1c1b1b',
        'on-primary-container': '#858383',
        'inverse-primary': '#c8c6c5',
        secondary: '#4e45d5',
        'on-secondary': '#ffffff',
        'secondary-container': '#6860ef',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#e3dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'on-secondary-fixed': '#100069',
        'on-secondary-fixed-variant': '#372abf',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002117',
        'on-tertiary-container': '#528f79',
        'tertiary-fixed': '#b0f0d6',
        'tertiary-fixed-dim': '#95d3ba',
        'on-tertiary-fixed': '#002117',
        'on-tertiary-fixed-variant': '#0b513d',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        arial: ['Arial', 'Helvetica', 'sans-serif'],
        display: ['var(--font-source-serif-4)', 'Georgia', 'serif'],
        'headline-lg': ['var(--font-source-serif-4)', 'Georgia', 'serif'],
        'headline-lg-mobile': ['var(--font-source-serif-4)', 'Georgia', 'serif'],
        'headline-md': ['var(--font-source-serif-4)', 'Georgia', 'serif'],
        'body-lg': ['var(--font-source-serif-4)', 'Georgia', 'serif'],
        'body-md': ['var(--font-source-serif-4)', 'Georgia', 'serif'],
        'ui-nav': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'ui-label': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        code: ['var(--font-jetbrains-mono)', 'var(--font-geist-mono)', 'monospace'],
      },
      fontSize: {
        display: ['3rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['2rem', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'ui-label': ['0.875rem', { lineHeight: '1', fontWeight: '500' }],
        'ui-nav': ['0.8125rem', { lineHeight: '1.5', letterSpacing: '0.01em', fontWeight: '400' }],
        code: ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        gutter: '2rem',
        'sidebar-width': '280px',
        'stack-sm': '0.5rem',
        'stack-md': '1.5rem',
        'stack-lg': '4rem',
      },
      maxWidth: {
        'container-max': '1200px',
        'content-narrow': '720px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      height: {
        header: '4rem',
      },
    },
  },
  plugins: [],
}

export default config
